### ISSUE TITLE
can not install plproxy  checksum error

### ISSUE THREAD

**Issue by zealot2007** [petere/pex#3]
~/.local/share/pex/packages(master)$ pex install plproxy
==> Downloading plproxy from http://pgfoundry.org/frs/download.php/3392/plproxy-2.5.tar.gz
######################################################################## 100.0%
pex: SHA1 mismatch
Expected: 6658ead83f12157e1e7fe6ef2e71b08083c2eae8
Actual: 8d4297d99520825f3012334e6d30613b6d2df462

**Comment by zealot2007** [comment]
I found that  http://pgfoundry.org/frs/download.php/3392/plproxy-2.5.tar.gz is 503

**Comment by petere** [comment]
Yeah, pgfoundry is currently quite unstable, so when it fails you might see this. If you think the error handling could be improved, let me know, but it might be hard to reproduce the exact situation. ;-)
