### ISSUE TITLE
Postgis and XCode 8

### ISSUE THREAD

**Issue by joaoponceleao** [petere/pex#7]
Hi,

Pex is unable to build Postgis on OSX 10.11.6 with the latest XCode 8.
It complains about not finding libxml2. Homebrew provides this, though not linked by default. Forcing a link creates a different error during the build.
Looking around, this seems to be related with issues with the recently released XCode 8 and libxml2 (of the top of my head, xcode is linking to libraries that used to be there in previous versions but are no longer available).
Is there anything that can be done on the pex side?

Joao.

**Comment by petere** [comment]
Can you show the exact command line and output?

**Comment by joaoponceleao** [comment]
I'm closing this issue as it is now building correctly. Sorry for the trouble.
